package dbutils

const train = `
	CREATE TABLE IF NOT EXISTS train(
		ID INTEGER PRIMARY_KEY AUTOINCREMENT,
		DRIVER_NAME VARCHAR(64) NULL,
		OPERATING_STATUS BOOLEAN
	)
`

const station = `
	CREATE TABLE IF NOT EXISTS station(
		ID INTEGER PRIMARY_KEY AUTOINCREMENT,
		NAME VARCHAR(64) NULL,
		OPENING_TIME TIME NULL,
		CLOSING_TIME TIME NULL
	)
`

const schedule = `
	CREATE TABLE IF NOT EXISTS schedule(
		ID INTEGER PRIMARY_KEY AUTOINCREMENT,
		TRAIN_ID INT,
		STATION_ID INT,
		ARRIVAL_TIME TIME
		FOREIGN_KEY (TRAIN_ID) REFERENCES train(ID)
		FOREIGN_KEY (STATION_ID) REFERENCES station(ID)
	)
`